# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NbCell": "00_read.ipynb",
         "dict2nb": "00_read.ipynb",
         "read_nb": "00_read.ipynb",
         "nbprocess_create_config": "00_read.ipynb",
         "get_config": "00_read.ipynb",
         "add_init": "00_read.ipynb",
         "write_cells": "00_read.ipynb",
         "basic_export_nb": "00_read.ipynb",
         "find_var": "01_maker.ipynb",
         "read_var": "01_maker.ipynb",
         "update_var": "01_maker.ipynb",
         "ModuleMaker": "01_maker.ipynb",
         "retr_exports": "01_maker.ipynb",
         "ModuleMaker.make_all": "01_maker.ipynb",
         "make_code_cell": "01_maker.ipynb",
         "make_code_cells": "01_maker.ipynb",
         "relative_import": "01_maker.ipynb",
         "update_import": "01_maker.ipynb",
         "NbCell.import2relative": "01_maker.ipynb",
         "ModuleMaker.make": "01_maker.ipynb",
         "basic_export_nb2": "01_maker.ipynb",
         "extract_comments": "02_export.ipynb",
         "NotebookProcessor": "02_export.ipynb",
         "NotebookProcessor.process_comment": "02_export.ipynb",
         "NotebookProcessor.process_cell": "02_export.ipynb",
         "NotebookProcessor.process": "02_export.ipynb",
         "ExportModuleProcessor": "02_export.ipynb",
         "ExportModuleProcessor.default_exp_code": "02_export.ipynb",
         "ExportModuleProcessor.exporti_code": "02_export.ipynb",
         "ExportModuleProcessor.export_code": "02_export.ipynb",
         "ExportModuleProcessor.create_modules": "02_export.ipynb",
         "nb_export": "02_export.ipynb",
         "nbs_export": "02_export.ipynb",
         "nb2dict": "03_sync.ipynb",
         "write_nb": "03_sync.ipynb",
         "absolute_import": "03_sync.ipynb",
         "update_lib": "03_sync.ipynb"}

modules = ["read.py",
           "maker.py",
           "export.py",
           "sync.py"]

doc_url = "https://nbprocess.github.io/"

git_url = "https://github.com/fastai/nbprocess/tree/master/"

def custom_doc_links(name): return None
