# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/_06_docs-Copy1.ipynb.

# %% auto 0
__all__ = ['rm_blank_proc', 'html_escape', 'insert_warning', 'write_md']

# %% ../nbs/_06_docs-Copy1.ipynb 3
from .read import *
from .imports import *
from .export import *
from .sync import write_nb, nb2dict

from fastcore.script import *
from fastcore.imports import *
from fastcore.basics import *
from fastcore.xtras import *

import uuid
import tempfile

# %% ../nbs/_06_docs-Copy1.ipynb 6
def rm_blank_proc(cell):
    "Remove empty cells"
    if(cell.source.strip()==''): cell.source = None

# %% ../nbs/_06_docs-Copy1.ipynb 7
@outp_proc('data', 'text/html')
def html_escape(cell, outp, item):
    "Place HTML in a codeblock and surround it with a <HTMLOutputBlock> component."
    cell.metadata.html_output = True
    return f'```html\n{item}\n```'

# %% ../nbs/_06_docs-Copy1.ipynb 10
def _get_cell_id(id_length=36): return uuid.uuid4().hex[:id_length]

def _get_md_cell(content="<!--- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT!-->"):
    return AttrDict({'cell_type': 'markdown', 'id': f'{_get_cell_id()}',
                     'metadata': {}, 'source': f'{content}'})

def insert_warning(nb):
    "Insert Autogenerated Warning Into Notebook after the first cell."
    nb.cells = nb.cells[:1] + [_get_md_cell()] + nb.cells[1:]

# %% ../nbs/_06_docs-Copy1.ipynb 11
def write_md(nb_path, procs=None, post_procs=None, outp_procs=None, pre_procs=None, tpl_file='ob.tpl'):
    nbp = NBProcessor(nb_path, procs, outp_procs=outp_procs)
    nb = nbp.nb
    for proc in L(pre_procs): proc(nb)
    nbp.process()
    for proc in L(post_procs): proc(nb)

    c = traitlets.config.Config()
    base = Path(__file__).parent.resolve()
    c.MarkdownExporter.template_file = str(base/'templates'/tpl_file)
    exp = MarkdownExporter(config=c)

    with tempfile.TemporaryFile('a+') as tmp:
        write_nb(nb, tmp)
        tmp.seek(0)
        md,_ = exp.from_file(tmp)

    dest = base/'../docusaurus/docs'/Path(nb_path).with_suffix('.md').name
    dest.write_text(md)
    return dest
