# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_docs.ipynb.

# %% auto 0
__all__ = ['strip_ansi_proc']

# %% ../nbs/06_docs.ipynb 3
from .read import *
from .imports import *
from .export import *

from fastcore.script import *
from fastcore.imports import *
from fastcore.xtras import *

# %% ../nbs/06_docs.ipynb 6
_re_ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')

def strip_ansi_proc(cell):
    "Strip Ansi Characters"
    for o in cell.get('outputs', []):
        if o.get('name') == 'stdout':
            o['text'] = _re_ansi_escape.sub('', o.text)
