# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_processors.ipynb.

# %% auto 0
__all__ = ['process_outputs', 'meta_', 'show_meta', 'insert_warning', 'remove_', 'hide_line', 'filter_stream_', 'clean_magics',
           'bash_identify']

# %% ../nbs/07_processors.ipynb 3
from .read import *
from .imports import *
from .process import *

from fastcore.imports import *
from fastcore.xtras import *

# %% ../nbs/07_processors.ipynb 5
def process_outputs(f, nbp, cell, args=None):
    "Helper function to use from a processor to process outputs in `cell`"
    for outp in getattr(cell, 'outputs', []): f(outp, args)

# %% ../nbs/07_processors.ipynb 7
def meta_(nbp, cell, key, *args): cell.metadata[key] = args

# %% ../nbs/07_processors.ipynb 8
def show_meta(cell):
    "Show cell metadata"
    if cell.metadata: print(cell.metadata)

# %% ../nbs/07_processors.ipynb 13
def insert_warning(nb):
    "Insert Autogenerated Warning Into Notebook after the first cell."
    content = "<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->"
    nb.cells.insert(1, AttrDict(cell_type='markdown', metadata={}, source=content))

# %% ../nbs/07_processors.ipynb 16
def remove_(nbp, cell, *args):
    for arg in args:
        if arg=='input': cell['source'] = ''
        elif arg=='output': del(cell['outputs'])
        elif arg=='cell': del(cell['source'])
        else: raise NameError(arg)

# %% ../nbs/07_processors.ipynb 18
_re_hideline = re.compile(r'#\|\s*hide_line\s*$', re.MULTILINE)
def hide_line(cell):
    "Hide lines of code in code cells with the directive `hide_line` at the end of a line of code"
    if cell.cell_type == 'code' and _re_hideline.search(cell.source):
        cell.source = '\n'.join([c for c in cell.source.splitlines() if not _re_hideline.search(c)])

# %% ../nbs/07_processors.ipynb 20
def _filter_stream(outp, args):
    if not args or outp.output_type != 'stream': return
    outp['text'] = [l for l in outp.text if not re.search('|'.join(args), l)]

def filter_stream_(nbp, cell, *words):
    "Remove output lines containing any of `words` in `cell` stream output"
    process_outputs(_filter_stream, nbp, cell, words)

# %% ../nbs/07_processors.ipynb 22
_magics_pattern = re.compile(r'^\s*(%%|%).*', re.MULTILINE)

def clean_magics(cell):
    "A preprocessor to remove cell magic commands"
    if cell.cell_type == 'code': cell.source = _magics_pattern.sub('', cell.source).strip()

# %% ../nbs/07_processors.ipynb 24
_bash_pattern = re.compile('^\s*!', flags=re.MULTILINE)

def bash_identify(cell):
    "A preprocessor to identify bash commands and mark them appropriately"
    if cell.cell_type == 'code' and _bash_pattern.search(cell.source):
        cell.metadata.magics_language = 'bash'
        cell['source'] = _bash_pattern.sub('', cell.source).strip()
